name: heart-disease-predection-build

on: [push]

jobs:
  build:
    name: compute engine deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/heart-disease-predection:latest heart-disease-predection_Dockerfile .

      - name: Push
        run: |
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/heart-disease-predection:latest
